In [2]:
print("hello world")


hello world


In [8]:
import tkinter as tk

class Calculator:
    def __init__(self, master):
        self.master = master
        master.title("Calculator")

        self.result_var = tk.StringVar()

        self.entry = tk.Entry(master, textvariable=self.result_var, font=('Arial', 24), bd=10, insertwidth=2, width=14, borderwidth=4)
        self.entry.grid(row=0, column=0, columnspan=4)

        self.create_buttons()

    def create_buttons(self):
        buttons = [
            '7', '8', '9', '/',
            '4', '5', '6', '*',
            '1', '2', '3', '-',
            '0', '.', '=', '+'
        ]

        row_val = 1
        col_val = 0

        for button in buttons:
            tk.Button(self.master, text=button, padx=20, pady=20, font=('Arial', 18),
                      command=lambda b=button: self.on_button_click(b)).grid(row=row_val, column=col_val)
            col_val += 1
            if col_val > 3:
                col_val = 0
                row_val += 1

        tk.Button(self.master, text='C', padx=20, pady=20, font=('Arial', 18),
                  command=self.clear).grid(row=row_val, column=0, columnspan=4)

    def on_button_click(self, char):
        if char == '=':
            try:
                result = eval(self.result_var.get())
                self.result_var.set(result)
            except Exception as e:
                self.result_var.set("Error")
        else:
            current_text = self.result_var.get()
            self.result_var.set(current_text + char)

    def clear(self):
        self.result_var.set("")


if __name__ == "__main__":
    root = tk.Tk()
    calculator = Calculator(root)
    root.mainloop()
    

In [ ]:
import tkinter as tk

class Calculator:
    def __init__(self, master):
        self.master = master
        master.title("Calculator")

        self.result_var = tk.StringVar()

        self.entry = tk.Entry(master, textvariable=self.result_var, font=('Arial', 24), bd=10, insertwidth=2, width=14, borderwidth=4)
        self.entry.grid(row=0, column=0, columnspan=4)

        self.create_buttons()

    def create_buttons(self):
        buttons = [
            '7', '8', '9', '/',
            '4', '5', '6', '*',
            '1', '2', '3', '-',
            '0', '.', '=', '+'
        ]

        row_val = 1
        col_val = 0

        for button in buttons:
            tk.Button(self.master, text=button, padx=20, pady=20, font=('Arial', 18),
                      command=lambda b=button: self.on_button_click(b)).grid(row=row_val, column=col_val)
            col_val += 1
            if col_val > 3:
                col_val = 0
                row_val += 1

        # Clear button
        tk.Button(self.master, text='C', padx=20, pady=20, font=('Arial', 18),
                  command=self.clear).grid(row=row_val, column=0, columnspan=2)

        # Backspace button
        tk.Button(self.master, text='←', padx=20, pady=20, font=('Arial', 18),
                  command=self.backspace).grid(row=row_val, column=2, columnspan=2)

    def on_button_click(self, char):
        if char == '=':
            try:
                result = eval(self.result_var.get())
                self.result_var.set(result)
            except Exception as e:
                self.result_var.set("Error")
        else:
            current_text = self.result_var.get()
            self.result_var.set(current_text + char)

    def clear(self):
        self.result_var.set("")

    def backspace(self):
        current_text = self.result_var.get()
        # Remove the last character
        self.result_var.set(current_text[:-1])


if __name__ == "__main__":
    root = tk.Tk()
    calculator = Calculator(root)
    root.mainloop()


: 

In [2]:
import numpy as np
numpy = np 
print(numpy)

<module 'numpy' from 'c:\\Users\\Salman\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>


In [3]:
import numpy as np 
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [6]:
import numpy as np 
array = np.array([1,2,3,4])
print(array, array.ndim)

[1 2 3 4] 1


In [8]:
import numpy as np 
array = np.array([(1,2,3,4),(6,7,8,9)])
print(array, array.ndim)

[[1 2 3 4]
 [6 7 8 9]] 2


In [9]:
import numpy as np 
array = np.array([(1,2,3,4),(6,7,8,9),(10,11,12,13)])
print(array, array.ndim)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]] 2


In [14]:
import numpy as np 
array = np.array([1,2,3,4,5])
print(array, array.ndim, array.size, array.shape, array.dtype)

[1 2 3 4 5] 1 5 (5,) int64


In [16]:
import numpy as np 
array = np.array([7])
print(array, array.ndim)

[7] 1


In [17]:
import numpy as np 
array = np.array([ [1,2],[3,4] ])
print(array, array.ndim)

[[1 2]
 [3 4]] 2


In [19]:
import numpy as np 
array = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(array, array.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3


In [24]:
import numpy as np 
array = np.array([1,"hello",3,4])
print(array, array.ndim)
print(array[1])

['1' 'hello' '3' '4'] 1
hello


In [53]:
import numpy as np 
array = np.array([ [1,2,3],[4,5,6] ])
print(array, array.ndim)
print(array[0,1])

[[1 2 3]
 [4 5 6]] 2
2


In [52]:
import numpy as np 
array = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]] ])
print(array, array.ndim)
print(array[1,0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 3
8
